{% set name = "esi-utils-geo" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi-utils-geo-{{ version }}.tar.gz
  sha256: 29e37b1aa73a4ba95e8906340e350098ef97debf3175cba5131687c1e7d84781

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.21.0
    - pandas >=1.4.1
    - geopy >=2.1.0

test:
  imports:
    - esi_utils_geo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/esi-utils-geo/
  summary: USGS Earthquake Basic Geographic Utilities
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
